# Data sources

## Mealyzer application and functionality

## Dataset description

bg readings

meals
meal details, evaluator nutrients, user nutriends, calculated fields (calculated calories, nutrient proportions)

activities

sleep

meal photos

## Dataset collection artifacts

pre and post meal bg times

evaluator


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(forcats)
library(r2d3)
library(parcoords)
library(dplyr)
```

## Data Import


```{r}
raw_data_path = "~/Dropbox/MealyzerData"
mealyser_data_overview = read_csv(file.path(raw_data_path, "mealyzer_data_overview.csv"), col_types = cols())
```


### Selecting users for the analysis

```{r}
users = mealyser_data_overview %>%
  filter(complete_meals > 14)
print(users[["user_id"]])
```

```{r}
read_mealyzer_files <- function(data_dir, user_ids, file_name, add_user_id, col_types) {
  result <- c()
  for (user_id in user_ids) {
    
    file_path = file.path(data_dir, as.character(user_id), file_name)
    df = read_csv(file_path, col_types = col_types)
    if (add_user_id) {
      df = cbind(user_id = user_id, df)
    }
    if (length(result) == 0) {
      result <- df
    } else {
      result <- rbind(result, df)
    }
  }
  return(result)
}

as.timestamp <- function(minutes_since, anchor_date = '2019-01-01 00:00:00 EST') {
  anchor_time = as.POSIXct(anchor_date)
  return(anchor_time + minutes_since * 60)
}

as.meals_kind <- function(values) {
  return(fct_relevel(values, c("breakfast", "morning_snack", "lunch", "afternoon_snack", "dinner", "after_dinner_snack")))
}

print_df <- function(df, ...) {
  print(df %>% select(...))
  return(df)
}

```

```{r}
bg_readings = read_mealyzer_files(raw_data_path, users[["user_id"]], "bg_labeled.csv", add_user_id = TRUE, col_types = cols(
  time = col_double(),
  bg = col_double(),
  meals_kind = col_character(),
  meal_id = col_double(),
  readings_kind = col_character()
)) %>%
  mutate(
    user_id = as.character(user_id),
    time = as.timestamp(time), 
    meals_kind = as.meals_kind(meals_kind),
    readings_kind = fct_relevel(readings_kind, c("premeal", "postmeal"))
  )
head(bg_readings)
```


```{r}
meals_data = read_mealyzer_files(raw_data_path, users[["user_id"]], "mealyzer_data.csv", add_user_id = FALSE, col_types = cols()) %>%
  mutate(
    user_id = as.character(user_id),
    eaten_at = as.timestamp(eaten_at),
    kind = as.meals_kind(kind),
    premeal_bg_time = as.timestamp(premeal_bg_time),
    postmeal_bg_time = as.timestamp(postmeal_bg_time),
    premeal_bg_delay_minutes = as.double(difftime(eaten_at, premeal_bg_time, units = "mins")),
    postmeal_bg_delay_minutes = as.double(difftime(postmeal_bg_time, eaten_at, units = "mins")),
    bg_impact = postmeal_bg - premeal_bg,
    bg_impact_slope = bg_impact / (premeal_bg_delay_minutes + postmeal_bg_delay_minutes)
  )
head(meals_data)
```