# Interactive

If the application inside this window is too small to work with, please <a href="https://kmamykin.shinyapps.io/shiny_app/" target="_blank">click here</a> to open it in a new tab.

```{r echo = FALSE}
knitr::include_app("https://kmamykin.shinyapps.io/shiny_app/", height = "600px")
```

## 6.1 Interesting Findings
We produced interactive plots using Shiny App as seen above. There are four tabs, which give information on nutrient overview for all selected users, overview of average pre-meal and post-meal blood glucose levels for the same users, and analysis reports by date and hour respectively. Each interactive plot allows the audience to select different fields like date range, meal types, and/or users. 

*Nutrient Overview* tab compares the nutrient proportion for all meals for each user evaluated by experts to that by the users themselves. We see that, in general, users tend to overestimate the proportion of fat and fiber and underestimate the proportion of carbs they consume compared to what experts evaluate. We can see more details regarding trends of each nutrient type consumed over time for each user in the third chart. 

*Blood Glucose Overview* tab produces two charts of average premeal and postmeal BG levels. The first one plots all BG levels over the selected date range, whereas the second one plots average BG levels for each hour throughout one day. The first piece of information we observe from these graphs is that people’s overall BG levels vary a lot. For example, user 1809
has much higher BG levels than the other users. However, on the bright side, 1809’s average premeal bg level is decreasing, which could be a positive sign of his/her health status. Other users like 1665 and 2308 shows increasing pre and post-meal BGs, which leads us to wonder what exactly they’ve been consuming. One thing worth noticing is that, people who have relatively high BG levels produce more volatile BG plots, whereas those with a lower BG level, produce more stable BG plots.

*Analyze by Date* tab presents four plots for selected users to tile information about BG levels, calories intake, and nutrients intake together for the audience to discover interesting trends and connect the dots. 

User #1809 serves as an example of people with relatively high BG levels. In the Calories Intake plot, we could see that over time, he/she ingests more calories for dinner and less calories for breakfast, and lunch is usually missing. In the Weights of Food Intake plot, we could see even though he/she consumes less carbs, weights of fat has been increasing. These bad eating habits could possibly validate such high BG levels compared with other users.
User #2254 also seems to be an interesting case, as the user seems to be adopting a more healthy lifestyle - less calories intake for all meal types, less carbs and fat consumed with pretty stable fiber intake, and lower premeal and postmeal bg levels over time.
We can also look at user #24. At first glance, it seems that the average premeal and postmeal bg level are pretty consistent over time. We see that the user consumed more calories for lunch as time went by, so we decided to leave breakfast and dinner data out and look at only lunch. We were able to see that the difference between premeal bg level and postmeal bg level became more obvious, and the user was consuming more carbs and protein over time. In regards to the proportion of nutrient, this user also consumed the most protein and fiber. All of these healthy lifestyle and eating habits explains why this user’s BG levels were low and stable.
For user #2890, we see that there is obvious upward trends for calories intake for all meals, which are consistent with the average premeal and postmeal BG levels when we filter in the breakfast meal type. Also, the user seems to be consuming more and more carbs across time, with the weights of carbs intake higher than those of other users. However, the user’s average BG levels seem to be pretty stable overtime regardless of his eating habit, which leads us to wonder if he engaged in a lot of manual labor during the day.

*Analyze by Hour* tab provides four plots that document the average pre-meal and post-meal BG level by hour, the average BG impact by hour, average calories intake by hour, and the weights of food intake by hour. This tab shows some interesting cases worth discussing: 
User #24 serves as a good example of users with a better eating habits. We see that user #24 consumes breakfast and morning snack regularly, and often eat less during dinner hours. Even though user #24 consumes more carbs during dinner hours, the weights of food intake for user #24 are still relatively consistent (we see relatively flat trends for the weights of food intake in a day). The generally lower pre and post-meal average BG level for user #24 may also suggest a better health situation compared to other users. 
On the contrary, user #2262 may seem like someone with a more irregular eating schedule. According to the average calories intake plot, user #2262 tend to consume more food in the second half of the day, with the dinner hour spanning between 17:00 and 23:00. The average BG impact by hour is also the highest during late afternoon/dinner time. We see that, even though on average the postmeal bg level for user #2262 and the weight of carbs the user consumed dropped throughout the day, the average premeal BG level increased especially during dinner hours. 
Plots for user #1821 present other interesting findings. We see that, compared to other users, user #1821 consumes a lot more calories throughout the day, especially during dinner hours, when user #1821 consumes the most carbs. However, the average pre and post meal BG level for user #1821 seems relatively consistent. The average pre-meal BG level even dropped toward the end of the days. If we were to make a guess, we would assume that user #1821 represent blue-collar worker with more physical/labor work or an athlete. 
