# Conclusion

The exploratory data analysis conducted in this project yielded several notable insights:

First, perhaps not surprisingly, it showed that the quality, accuracy, and completeness of the dataset collected with self-monitoring is deeply impacted by the features available to users for data collection. Furthermore, the analysis showed that particular design choices of the data collection app have a profound impact on the collected data. For example, our analysis showed considerable variability in time when blood glucose readings were captured in relation to meals (both before and after). This was likely due to the inconvenience of using a smartphone app at mealtime: the need to photograph a meal and enter its ingredients probably left many users with cold meals, which led to workarounds suggested by our analysis (recording meals and BG levels only after meals were consumed). This suggest that datasets can be best understood in the context of how this data was collected and with full awareness of features available for data collection. 

Second, the analysis suggested that aggregating data across individuals yields few insights. However, viewing data for each individual can reveal interesting patterns in regards to their behaviors, and how these behaviors impact their blood glucose levels. This may suggest the need for computational data analysis methods that examine patterns on an individual level may have advantage over methods that require aggregation of data across individuals. 

Furthermore, the relatively simple data analysis techniques used in this project did not reveal any consistent patterns of association between individuals’ captured records (i.e., nutrition in meals) and changes in their blood glucose levels. This may suggest the need for more extensive datasets (more data per person and across individuals) to identify any stable signal. However, it may also suggest that these relationships may be more complex, and possibly non-linear. This suggests the need for more sophisticated computational analysis methods that are better suited for sparse data and non-linear relationships. 

Finally, the lack of straightforward and easy to identify associations in the data may suggest the need for interactive tools for exploratory data analysis. Such tools can help experts (e.g., diabetes educators) to examine different aspects of the dataset and probe different associations consistent with their expert knowledge and expectations. We have explored some of the features for interactive data analysis; future work could further build on our initial explorations. 
