---
title: "DataProcessing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(forcats)
```

## Data Import


```{r}
raw_data_path = "~/Dropbox/MealyzerData"
mealyser_data_overview = read_csv(file.path(raw_data_path, "mealyzer_data_overview.csv"), col_types = cols())
```


### Selecting users for the analysis

```{r}
users = mealyser_data_overview %>%
  filter(complete_meals > 14)
print(users[["user_id"]])
```
```{r}
read_mealyzer_files <- function(data_dir, user_ids, file_name, add_user_id, col_types) {
  result <- c()
  for (user_id in user_ids) {
    file_path = file.path(data_dir, as.character(user_id), file_name)
    df = read_csv(file_path, col_types = col_types)
    if (add_user_id) {
      df = cbind(user_id = user_id, df)
    }
    if (length(result) == 0) {
      result <- df
    } else {
      result <- rbind(result, df)
    }
  }
  return(result)
}

as.timestamp <- function(minutes_since, anchor_date = '2019-01-01 00:00:00 EST') {
  anchor_time = as.POSIXct(anchor_date)
  return(anchor_time + minutes_since * 60)
}

as.meals_kind <- function(values) {
  return(fct_relevel(values, c("breakfast", "morning_snack", "lunch", "afternoon_snack", "dinner", "after_dinner_snack")))
}

print_df <- function(df, ...) {
  print(df %>% select(...))
  return(df)
}
```

```{r}
bg_readings = read_mealyzer_files(raw_data_path, users[["user_id"]], "bg_labeled.csv", add_user_id = TRUE, col_types = cols(
  time = col_double(),
  bg = col_double(),
  meals_kind = col_character(),
  meal_id = col_double(),
  readings_kind = col_character()
)) %>%
  mutate(
    user_id = as.character(user_id),
    time = as.timestamp(time), 
    meals_kind = as.meals_kind(meals_kind),
    readings_kind = fct_relevel(readings_kind, c("premeal", "postmeal"))
  )
head(bg_readings)
```

```{r}
meals_data = read_mealyzer_files(raw_data_path, users[["user_id"]], "mealyzer_data.csv", add_user_id = FALSE, col_types = cols()) %>%
  mutate(
    user_id = as.character(user_id),
    eaten_at = as.timestamp(eaten_at),
    kind = as.meals_kind(kind),
    premeal_bg_time = as.timestamp(premeal_bg_time),
    postmeal_bg_time = as.timestamp(postmeal_bg_time),
    premeal_bg_delay_minutes = as.double(difftime(eaten_at, premeal_bg_time, units = "mins")),
    postmeal_bg_delay_minutes = as.double(difftime(postmeal_bg_time, eaten_at, units = "mins"))
  )
head(meals_data)
```

### Dataset highlevel view

```{r}
meals_data %>%
  mutate(eaten_at_hour = hour(eaten_at)) %>%
  ggplot() +
  geom_histogram(aes(x=eaten_at_hour), bins = 24) +
  facet_wrap(~user_id, ncol = 7) + 
  labs(
    title = "Distribution of hours when users had a meal"
  )
```

```{r}
premeal_delay_buckets = c("< 15 min", "10 - 60 min", "> 60 min")
meals_data %>%
  #filter(user_id == 2392) %>%
  #filter(premeal_bg_delay_minutes <= 300 & premeal_bg_delay_minutes >= 0) %>%
  #mutate(premeal_bg_delay = ifelse(premeal_bg_delay_minutes < 15, premeal_delay_buckets[1], ifelse(premeal_bg_delay_minutes < 60, premeal_delay_buckets[2], premeal_delay_buckets[3]))) %>%
  #mutate(premeal_bg_delay = fct_relevel(premeal_bg_delay, premeal_delay_buckets)) %>%
  print_df(user_id, premeal_bg_time, eaten_at, premeal_bg_delay_minutes) %>%
  ggplot() +
  #geom_bar(aes(x=premeal_bg_delay, fill=premeal_bg_delay)) +
  geom_histogram(aes(x=premeal_bg_delay_minutes), binwidth = 30) +
  scale_x_continuous(breaks=c(0, 60, 120, 180, 240, 300), labels = c("0", "1h", "2h", "3h", "4h", "5h"), limits = c(0, 300)) + 
  facet_wrap(~user_id, ncol = 7, scales = "free_y") + 
  labs(
    title = "Delay of premeal BG recordings, bucketed"
  ) + 
  theme(
    legend.position="top",
    #axis.title.x = element_blank(),
    #axis.text.x = element_blank(),
    #axis.ticks.x = element_blank()
    axis.title.y = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank()
  )
```

```{r}
postmeal_delay_buckets = c("< 1 hour", "1 - 2 hours", "> 2 hours")
meals_data %>%
  #mutate(postmeal_bg_delay = ifelse(postmeal_bg_delay_minutes < 60, postmeal_delay_buckets[1], ifelse(postmeal_bg_delay_minutes < 120, postmeal_delay_buckets[2], postmeal_delay_buckets[3]))) %>%
  #mutate(postmeal_bg_delay = fct_relevel(postmeal_bg_delay, postmeal_delay_buckets)) %>%
  print_df(user_id, eaten_at, postmeal_bg_time, postmeal_bg_delay_minutes) %>%
  ggplot() +
  #geom_bar(aes(x=postmeal_bg_delay, fill=postmeal_bg_delay)) +
  geom_histogram(aes(x=postmeal_bg_delay_minutes), binwidth = 30) +
  #geom_density(aes(x = postmeal_bg_delay_minutes)) +
  facet_wrap(~user_id, ncol = 7) + 
  scale_x_continuous(breaks=c(0, 60, 120, 180, 240, 300), labels = c("0", "1h", "2h", "3h", "4h", "5h"), limits = c(0, 300)) + 
  labs(
    title = "Delay of postmeal BG recordings, bucketed"
  ) + 
  theme(
    legend.position="top",
    axis.title.x = element_blank(),
    #axis.text.x = element_blank(),
    #axis.ticks.x = element_blank()
    #axis.title.y = element_blank(),
    #axis.text.y = element_blank(),
    #axis.ticks.y = element_blank()
  )
```

```{r fig.height=12, fig.width=6}
meals_data %>%
  ggplot() +
  geom_boxplot(aes(x = user_id, y = premeal_bg_delay_minutes), varwidth = TRUE) + 
  scale_y_continuous(breaks=c(0, 15, 30, 45, 60), labels = c("0", "15min", "30min", "45min", "1h"), limits = c(0, 60)) + 
  coord_flip() +
  labs( title = "" )
```

```{r fig.height=12, fig.width=6}
meals_data %>%
  ggplot() +
  geom_boxplot(aes(x = user_id, y = postmeal_bg_delay_minutes), varwidth = TRUE) + 
  scale_y_continuous(breaks=c(0, 60, 120, 180, 240), labels = c("0", "1h", "2h", "3h", "4h"), limits = c(0, 1000)) + 
  coord_flip() +
  labs( title = "" )
```

The premeal BG delay varies greatly, for some users 