--- 
title: "Exploration of data collected with self monitoring app in diabetes"
author: "Kliment Mamykin, Sunny Lee, Jinrong Cao"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

The data in this dataset was collected with several mobile applications built for monitoring and self management of type 2 diabetes. All these mobile apps were created within the research lab at the Columbia University Medical Center. All apps included nearly identical set of features for data collection but all provided different types of feedback to users: 

1.	Glucoracle app asked individuals to record their meals by photographing them and providing a brief text description and ingredients. For each meal, users were asked to estimate nutritional composition of the meal to the best of their abilities, and record blood glucose (BG) levels captured with a conventional glucometer before and after the meal. All these data were used to train a personalized predictive model of BG regulation, which provided users with personalized predictions for post-meal BG levels. Glucoracle was deployed with individuals with type 2 diabetes recruited for pilot studies (n=20). 

2.	Platano app had several versions. V1 allowed users to simply record their meals (photographs and brief descriptions and ingredients) and BG levels pre and post meals. Platano app v2 asked users to set nutritional goals (suggested by registered dietitians). Once the goals were set, it also allowed users to record meals and BG before and after meals; for each captured meal it asked users to assess whether this meal met their nutritional goals. Platano users were also provided with Fitbit tracking devices for tracking physical activity and sleep. All meals recorded with the app were evaluated by a team of nutritional experts to estimate the amount of calories and the nutritional breakdown (grams of protein, fat, carbs, fiber) in the meals. Platano was deployed in a pilot study with individuals with type 2 diabetes (n=40). 

While these apps varied in their features, the dataset collected exhibits many common fields. The goal for this project is to perform exploratory data visualization of this dataset.